# This is a basic workflow that is manually triggered


on:
  # Triggers the workflow every day at 1am
  schedule:
#    - cron: "0 1 * * *"
    - cron: "*/1 * * * *"


jobs:
  # This workflow contains a single job called "trigger-cron"
  trigger-cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Capture dates
        run: |
          yesterday=${date --date='1 day ago' +'%Y-%m-%dT%T'}
          today=${date +'%Y-%m-%dT%T'}
          echo "curl https://search-data-parity.shuttercorp.net//compare/snowflake-solr/reindex?from=$yesterday&to=$today"

